# site settings
title: Guillermo Garcia
subtitle: aka bitcoder
email: bitcoder@gmail.com
description: |
  Based in Quito, Ecuador. Born 1977.<br>
  Focused on enabling teams to work together effortlessly.
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Guillermo Garcia
street_address:
city: Quito
state: Pichincha
zip_code: 55555
country: Ecuador
phone: +59399.897.9627

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url: https://500px.com/bitcoder
facebook_url: https://www.facebook.com/AxtraRD
github_url: https://github.com/bitcod3r/
gitlab_url:
googleplus_url:
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/bitcoder/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/bitcoder

# build settings
markdown: kramdown

sass:
  style: compressed
